// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnApKh3ia2tEUa4MnW9KavGeX7ly0bxVg',
    appId: '1:98570590040:web:0e2574174fa1ca52e5772d',
    messagingSenderId: '98570590040',
    projectId: 'my-research-0',
    authDomain: 'my-research-0.firebaseapp.com',
    storageBucket: 'my-research-0.firebasestorage.app',
    measurementId: 'G-ZCPXQV9BHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdMOjl5TRDXH9IXKVQs7kMOGhv4I4WpM',
    appId: '1:98570590040:android:caee1e094029ab93e5772d',
    messagingSenderId: '98570590040',
    projectId: 'my-research-0',
    storageBucket: 'my-research-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGjekNnHHmCw-gpzetMxb3jGJoaLIpPc',
    appId: '1:98570590040:ios:18bb340a5be869e2e5772d',
    messagingSenderId: '98570590040',
    projectId: 'my-research-0',
    storageBucket: 'my-research-0.firebasestorage.app',
    iosBundleId: 'com.example.myResearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjGjekNnHHmCw-gpzetMxb3jGJoaLIpPc',
    appId: '1:98570590040:ios:18bb340a5be869e2e5772d',
    messagingSenderId: '98570590040',
    projectId: 'my-research-0',
    storageBucket: 'my-research-0.firebasestorage.app',
    iosBundleId: 'com.example.myResearch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnApKh3ia2tEUa4MnW9KavGeX7ly0bxVg',
    appId: '1:98570590040:web:ab99552c3e89c173e5772d',
    messagingSenderId: '98570590040',
    projectId: 'my-research-0',
    authDomain: 'my-research-0.firebaseapp.com',
    storageBucket: 'my-research-0.firebasestorage.app',
    measurementId: 'G-BK9DG4CVT5',
  );
}
